name: adv-attacks
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.3.3
  - matplotlib=3.10.6
  - pillow=11.3.0
  - pytorch=2.9.1
  - torchvision=0.24.1
  - pytorch-cuda=12.8